---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  nodeSelector:
    purpose: poc
  containers:
    - name: jenkins-pod
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"