---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    os: nginx
    type: replication-controller
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    os: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        os: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx:1.25
          ports:
            - containerPort: 8080
