---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
  annotations:
    kubernetes.io/change-cause: "updated fluentd Latest image"
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: fluentd      
  template:
    metadata:
      name: fluentd
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluentd:latest
