---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod-env-variable
  labels:
    app: alpine
    type: env-variable
spec:
  containers:
    - name: alpine
      image: alpine:3.14
      env:
        - name: PURPOSE
          value: TEST
      args:
        - sleep
        - 1d
