---
apiVersion: v1
kind: Pod
metadata:
  name: alpine=pod
  labels:
    app: alpine
    version: all
spec:
  restartPolicy: OnFailure
  containers:
    - name: alpine
      image: alpine:3.14
      args:
        - sleep
        - 1d
