---
apiVersion: v1
kind: Pod
metadata:
  name: all-os-pod
  labels:
    app: alpine-nginx-httpd
    version: all
spec:
  restartPolicy: OnFailure
  containers:
    - name: alpine
      image: alpine:3.14
      args:
        - sleep
        - 1d
    - name: nginx
      image: nginx:1.23
      ports:
        - name: nginxport
          containerPort: 80
          protocol: TCP
    - name: httpd
      image: httpd:2.4
      ports:
        - containerPort: 80