---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd
    version: all
spec:
  restartPolicy: OnFailure
  containers:
    - name: httpd
      image: httpd:2.4
      ports:
        - name: httpdport
          containerPort: 80
          protocol: TCP
