---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    version: all
spec:
  restartPolicy: OnFailure
  containers:
    - name: nginx
      image: nginx:1.23
      ports:
        - name: nginxport
          containerPort: 80
          protocol: TCP
