---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    layer: db
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: mysql-config-map
            optional: false
      volumeMounts:
        - name: mysql-dyn-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-dyn-vol
      persistentVolumeClaim:
        claimName: mysql-vol-pvc