---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    type: pod
spec:
  containers:
    - name: mysql-pod
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: rootroot
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pvol
  volumes:
    - name: mysql-pvol
      persistentVolumeClaim:
        claimName: mysql-pvc
