---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: web-server
    os: nginx
    version: '1.23'
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: nginx-pod
      labels:
        app: web-server
        type: pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80
            
