---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
    purpose: nodeselector
  annotations:
    kubernetes.io/change-cause: "updated fluentd Latest image"
spec:
  nodeSelector:
    purpose: dev
  containers:
    - name: jenkins
      image: jenkins/jenkins:lts-jdk11
      ports:
        - containerPort: 8080
          hostPort: 80
