---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-alpine-rs
  labels:
    os: jenkins-alpine
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      os: jenkins-alpine
  template:
    metadata:
      name: jenkins-alpine-pod
      labels:
        os: jenkins-alpine
    spec:
      containers:
        - name: jenkins-pod
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080
        - name: alpine-pod
          image: alpine
          args:
            - sleep
            - 1d
