---
apiVersion: v1
kind: Pod
metadata: 
  name: restart-always
  labels: 
    app: alpine
    version: 3.14
spec: 
  restartPolicy: Always
  containers: 
    - name: alpine-pod-always
      image: alpine:3.14
      args: 
        - sleep
        - 5s