---
apiVersion: v1
kind: Pod
metadata:
  name: restart-never
  labels:
    app: alpine
spec:
  restartPolicy: Never
  containers:
    - name: alpine-pod-always
      image: alpine:3.14
      args:
        - sleep
        - 5s