---
apiVersion: v1
kind: Pod
metadata:
  name: restart-onfailure
  labels:
    app: alpine
spec:
  restartPolicy: OnFailure
  containers:
    - name: alpine-pod-always
      image: alpine:3.14
      args:
        - sleep
        - 5MMS