---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
    type: pod
spec:
  containers:
    - name: postgres-pod
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: devops
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pvclaim
  volumes:
    - name: postgres-pvclaim
      persistentVolumeClaim:
        claimName: postgres-pvc