---
apiVersion: v1
kind: Pod
metadata:
  name: myspc-pod
  labels:
    app: spc
    type: pod
spec:
  containers:
    - name: myspc
      image: abhicontainerregistryqtdevops.azurecr.io/spc:latest
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: regcred
