---
apiVersion: v1
kind: Pod
metadata:
  name: on-failure
  labels:
    app: alpine
spec:
  containers:
    - name: failure 
      image: alpine
      args:
        - sleep
        - 5sms
---
apiVersion: v1
kind: Pod
metadata:
  name: on-success
  labels:
    app: alpine
spec:
  restartPolicy: OnFailure
  containers:
    - name: success 
      image: alpine
      args:
        - sleep
        - 5s
