---
apiVersion: v1
kind: Pod
metadata:
  name: never-restart-pod
  labels:
    app: alpine
spec:
  restartPolicy: Never
  containers:
    - name: alpine-fail
      image: alpine
      args:
        - sleep
        - 5s

