---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    type: pod
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: mysql-secret

