---
apiVersion: v1
kind: Pod
metadata:
  name: limits-pod-nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-pod
      image: nginx:1.23
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
