---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    type: svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80