---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-2
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
        - name: nginx-pod
          image: nginx:1.23
          ports:
            - containerPort: 80
