---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenins-alpine-rs
  labels:
    app: jenkins
spec:
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk17
          ports:
            - containerPort: 8080
        - name: alpine
          image: alpine:3.17
          args:
            - sleep
            - 1d
 

  