---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - name: nginx
          image: httpd:2.4
          ports:
            - containerPort: 80
              protocol: TCP

