---
apiVersion: v1
kind: Pod
metadata: 
  name: testAlpine
  labels: 
    app: alpine-pod
    version: latest
spec: 
  activeDeadlineSeconds: 2
  containers: 
    - name: alpine1
      image: alpine
      command: 
        - sleep
        - 1d
