---
apiVersion: v1
kind: Pod
metadata: 
  name: test-alpine
  labels: 
    app: alpine-pod
    version: latest
spec: 
  activeDeadlineSeconds: 2
  containers: 
    - name: alpine1
      image: alpine
      args: 
        - sleep
        - 1d
