apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: sql-pod
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: rootroot
